---
- name: Ensures nginx dir exists
  file:
    path: '{{ item }}'
    state: directory
  with_items:
  - '{{ nginx_dir }}'
  - '{{ nginx_dir }}/config'
  - '{{ nginx_dir }}/certs'
  - '{{ nginx_dir }}/certs/dns-conf'
  - '{{ nginx_dir }}/cache'
  - '{{ nginx_dir }}/logs'
  - "{{ nginx_dir }}/static"

- name: Copy conf files
  template:
    src: "{{ nginx_config_location }}"
    dest: "{{ nginx_dir }}/config/nginx.conf"
    mode: 777
  notify:
    - restart nginx

- name: nginx container
  docker_container:
    name: "{{ nginx_container_name }}"
    image: "{{ nginx_docker_image }}"
    state: started
    hostname: "{{ nginx_hostname }}"
    restart_policy: unless-stopped
    ports: "{{ nginx_ports }}"
    volumes:
      - "{{ nginx_dir }}/config/nginx.conf:/etc/nginx/nginx.conf"
      - "{{ nginx_dir }}/config/options-ssl-nginx.conf:/etc/nginx/options-ssl-nginx.conf"
      - "{{ nginx_dir }}/static:/static"
      - "{{ nginx_dir }}/cache/:/etc/nginx/cache"
      - "{{ nginx_dir }}/certs/etc/letsencrypt/:/etc/letsencrypt/"
      - "{{ nginx_dir }}/logs/:/etc/nginx/log"
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - name: "{{ nginx_docker_network }}"
    purge_networks: true
  notify:
    - restart nginx